microsoft/PowerShellForGitHub

README.md

If you try and use Notepad.exe  or Visual Studio to save the psm1 file, you will get an error about insufficient permissions even if you are logged in as Admin.
I worked around this by using ISE as Administrator

readme - permissions fix

---

README.md

Some of the secret teams that the Pester tests depend on
appear to no longer be valid (they were set up by the
previous module administrator many years ago).
Until this is resolved, removing the CI status from the
README in order to avoid potential end-user confusion on
the current status/quality of the module.

Temporarily disabling display of CI tests

---

CHANGELOG.md
GitHubCore.ps1
GitHubRepositoryForks.ps1
PowerShellForGitHub.psd1
Tests/GitHubRepositoryForks.ps1
USAGE.md

Pull Request #31 was adding support for getting forks using
the old module structure.
I've gone ahead and added the requested functionality using
the new module layout, and additionally added support for
creating new forks, along with tests for both.

Add support for querying and creating forks

---

CHANGELOG.md
GitHubRepositoryForks.ps1
Tests/GitHubRepositoryForks.tests.ps1

* Minor static analysis issues fixed.
* Corrected name of the test file for `GitHubRepositoryForks`
* Ensured the `getParams` are used during execution of `Get-GitHubRepositoryFork`

Fix static analysis misses with new Fork featurework

---

NugetTools.ps1

`Test-Path` will write to the error stream if there is a file access issue,
but still return back `$false`.  Within this method, we simply want to test
if the file exists -- not having access to the file is an equivalence case
for us and should be silent.
This updates `Test-Path` to use `-ErrorAction Ignore` to silence any potential
errors that we don't care about.
Additionally this updates `Test-AssemblyIsDesiredVersion` to also be robust
to file access issues.  If it has issues getting the file information, even
after getting passed the `Test-Path` in the parameter validation, we want to
gracefully return `$false` without undo error logging (we will write a
Warning log entry though for completeness).

Improve robustness of `Get-NugetPackageDllPath` to file access issues

---

GitHubConfiguration.ps1
Helpers.ps1
Telemetry.ps1

All API accessing methods allow users to provide an AccessToken to be used
for the duration of that API call.  The problem with that is that the
command is also logged by default, which means that the AccessToken value
might be logged in plain text to the log file.
To fix this, `Write-InvocationLog` has been modified in a few ways:
* Can now redact the value of specified parameters, or exclude the parameter altogether.
* `AccessToken` has been configured to _always_ be redacted, and
`NoStatus` has been configured to _always_ be excluded (to avoid noise)
* Instead of logging the originally invoked line, as well as the individual
values of the parameters, this now logs a single line with a modified version
of the invocation with the substitution of parameter values performed in-place.
* The …

Update logging to redact AccessToken if provided at commandline

---

CHANGELOG.md
CONTRIBUTING.md
GitHubRepositoryTraffic.ps1
PowerShellForGitHub.psd1
Tests/GitHubRepositoryTraffic.tests.ps1

* Updates the module version in the `.psd1` file
* Updates CHANGELOG and CONTRIBUTING
* Renamed `GitHubTraffic.ps1` -> `GitHubRepositoryTraffic.ps1`
(and similar change for the test file) to follow the API
hierarchy
* Minor change to get param passing based on post-commit
PR feedback

Updating module to 0.4.0

---

GitHubAnalytics.ps1
GitHubBranches.ps1
GitHubConfiguration.ps1
GitHubCore.ps1
GitHubIssues.ps1
GitHubLabels.ps1
GitHubMiscellaneous.ps1
GitHubOrganizations.ps1
GitHubPullRequests.ps1
GitHubRepositoryForks.ps1
GitHubRepositoryTraffic.ps1
GitHubTeams.ps1
GitHubUsers.ps1
Helpers.ps1
Telemetry.ps1

* Updated `Resolve-ParameterWithDefaultConfigurationValue` and `Resolve-RepositoryElements`
to grab `$PSBoundParameters` from the previous (calling) scope if not provided.
* Updated `Write-InvocationLog` to grab `$MyInvocation` from the previous (calling) scope
if not explicitly provided.
In all cases, this will simplify the standard calling pattern for these functions.

Update helper methods to grab appropriate default values from calling scope

---

CONTRIBUTING.md
GitHubConfiguration.ps1
GitHubCore.ps1

If enabled, the JSON-serialized version of the body of any REST request will
be written to verbose output, so that you can see exactly what is being sent
to GitHub.

Add `LogRequestBody` configuration option to make development debugging easier

---

README.md

Changing over to the `www` links as they are more up-to-date.

Updating badges links

---

GitHubComments.ps1
GitHubIssues.ps1
GitHubLabels.ps1
PowerShellForGitHub.psd1
Tests/Config/Settings.ps1
Tests/GitHubLabels.tests.ps1
USAGE.md

Added functionality for the [issue label APIs](https://developer.github.com/v3/issues/labels/)

Add support for issue labels

---

GitHubIssues.ps1

Since we changed the type of issue from string to int, the int will initialize at 0 and will fail our null check. This makes the code think that the Issue Param is always supplied. We should use $PSBoundParameters.ContainsKey to check this instead. This will fix issue #72.

Issue param in Get-GitHubIssue will always be set to 0

---

Tests/GitHubAnalytics.tests.ps1
Tests/GitHubAssignees.tests.ps1
Tests/GitHubComments.tests.ps1
Tests/GitHubCore.Tests.ps1
Tests/GitHubEvents.tests.ps1
Tests/GitHubLabels.tests.ps1
Tests/GitHubMilestones.tests.ps1
Tests/GitHubRepositoryForks.tests.ps1
Tests/GitHubRepositoryTraffic.tests.ps1

Issue #76 recent fixed a bug where Labels were not being correctly added to Issues at the time of creation.
This new UT will ensure that is always tested going forward.
Additionally, this updates all UT's to disable telemetry and enable logging of the request body to ease debugging.

Add UT for testing labels added at Issue creation time

---

GitHubIssues.ps1
Tests/GitHubLabels.tests.ps1

Similar to #76, `Update-GitHubIssue` was passing in the provided labels as `label` instead of `labels` in the request body.
This fixes the issue and also adds a UT to catch that scenario.

Fix issue preventing labels from being updated when updating Issue

---

GitHubCore.ps1

These can be seen when running `Get-GitHubIssue` and looking at:
* `url`
* `repository_url`
* `labels_url`
* `comments_url`
* `events_url`

Update Split-GitHubUri to work with the api.github.com URI's as well

---

GitHubOrganizations.ps1
GitHubTeams.ps1
PowerShellForGitHub.psd1

* _Added_ `Test-GitHubOrganizationMember` to check to see if a user is in an organization.
* No UT was added for this, because we would only be able to test for the negative case since the API can't create new users.
* _Updated_ `Get-GitHubTeamMember` to optionally work directly with a `TeamId` (instead of it always implicitly looking it up when being given the `TeamName`).
* Similarly for Teams -- more of the API set needs to be built out before this can be individually tested.

Add Test-GitHubOrganizationMember

---

GitHubOrganizations.ps1

Was failing on PSUseOutputTypeCorrectly:
The cmdlet 'Test-GitHubOrganizationMember' returns an object of type 'System.Boolean'
but this type is not declared in the OutputType attribute.

Fixing PSScriptAnalyzer error for Test-GitHubOrganizationMember

---

GitHubAssignees.ps1
GitHubComments.ps1
GitHubEvents.ps1
GitHubIssues.ps1
GitHubLabels.ps1
GitHubMilestones.ps1
GitHubRepositories.ps1
GitHubTeams.ps1

Updating all instances of ID's typed as [int] to be [int64].
Fixes #91

Updating [int] to [int64]

---

CONTRIBUTING.md
GitHubConfiguration.ps1
GitHubCore.ps1
README.md

I think I ran the pester tests correctly, or at least they all came back green for me anyhow. Static analysis also came back empty.
This resolves #98 with the ability to supply a new configuration parameter, `GitHubBaseUrl`. It will default to `github.com`. GitHub Enterprise installs to a different URL and the API remains as `api.somegithub.com`, thus it's simple to hit that API on a different base URL.
I've been using a similar set of changes along with a few other quality of life ones in my organization over the past week as we prototyped out some tools around automating GitHub Enterprise. It performed admirably with these changes here.
Fixed a related typo in the documentation as well.

Add URL config for GitHub Enterprise

---

GitHubAssignees.ps1
GitHubBranches.ps1
GitHubComments.ps1
GitHubEvents.ps1
GitHubIssues.ps1
GitHubLabels.ps1
GitHubMilestones.ps1
GitHubMiscellaneous.ps1
GitHubPullRequests.ps1
GitHubRepositories.ps1
GitHubRepositoryForks.ps1
GitHubRepositoryTraffic.ps1
Tests/GitHubRepositoryForks.tests.ps1
USAGE.md

This project has been transferred from the PowerShell organization to the
Microsoft organization.  This update fixes any references to the organization
name.

Update organization name in project from PowerShell to Microsoft

---

Tests/Common.ps1
Tests/GitHubAnalytics.tests.ps1
Tests/GitHubAssignees.tests.ps1
Tests/GitHubComments.tests.ps1
Tests/GitHubCore.Tests.ps1
Tests/GitHubEvents.tests.ps1
Tests/GitHubLabels.tests.ps1
Tests/GitHubMilestones.tests.ps1
Tests/GitHubRepositoryForks.tests.ps1
Tests/GitHubRepositoryTraffic.tests.ps1

The Pester test files contained _a lot_ of duplicated test
setup/configuration.  This update factors all of that out
to Test/Common.ps1 so that _just about_ the entire content
of a Pester test file can be unique to the code being tested.

Refactor common Pester test infrastructure

---

.gitignore

These dll's are used for reporting diagnostic data and users can
optionally store them in the module's directory to avoid downloading
them on demand (or they can use Set-GitHubConfiguration -AssemblyPath
to specify an alternate location).
For users that opt to put the dll's in the module directory and are using
the module from a git enlistment, this will ignore those files.
This should be temporary and should be able to be undone once #104 is resolved.

Add diagnostic data dll names to .gitignore

---

.vscode/settings.json
GitHubCore.ps1

Per the [documentation](https://developer.github.com/enterprise/2.16/v3/#current-version), enterprise installations support a base URL of  `http(s)://[hostname]/api/v3` in addition to the existing support of `http(s)://api.[hostname]/`.  This PR updates the module to _always_ use the `http(s)://[hostname]/api/v3` syntax when `[hostname]` is _not_ `github.com`.
Fixes #117

Fix hostname support for Enterprise installations of GitHub

---

USAGE.md

Fix #102 
I used this module to migrate my blog comments to Github Issues

Adding advanced example

---

Tests/GitHubAnalytics.tests.ps1
Tests/GitHubAssignees.tests.ps1
Tests/GitHubComments.tests.ps1
Tests/GitHubCore.Tests.ps1
Tests/GitHubEvents.tests.ps1
Tests/GitHubLabels.tests.ps1
Tests/GitHubMilestones.tests.ps1
Tests/GitHubRepositoryForks.tests.ps1
Tests/GitHubRepositoryTraffic.tests.ps1

Adopting `$PSScriptRoot` to simplify path access,
and making a minor code simplification in a test.

Minor test cleanup

---

GitHubMilestones.ps1
Tests/GitHubMilestones.tests.ps1

The "Should have the expected due_on date" UT was failing, but
only at certain times of the day.  Further investigation uncovered
this support forum post:
https://github.community/t5/How-to-use-Git-and-GitHub/Milestone-quot-Due-On-quot-field-defaults-to-7-00-when-set-by-v3/m-p/6901
In the event that the post goes away at some point, I will archive
what it says here:
> This is an artifact of how GitHub was originally designed.
> To my recollection, all timestamps in the database are
> normalized to Pacific time. So yes, this is the expected behavior.
> [The time used will vary] because midnight Pacific time is
> 7AM or 8AM UTC time depending on whether Pacific time is in
> daylight savings or not on that date.
Given this information, the problem was then quite clear.
Examples:
* If you set …

Ensure Milestone due_on always gets set to desired date

---

GitHubRepositories.ps1

Due to a copy-paste error, the function was incorrectly inverting the
user's choice.
A separate work item will be created to track adding some additional
tests to this part of the code.
Fixes #134

Fix Update-GitHubRepository to properly handle the -Archived switch

---

GitHubRepositories.ps1

There was a typo in `$RepositoryName` which was being referenced to
generate the REST endpoint used for `Update-GitHubRepository`.

Fix Update-GitHubRepository typo resulting in incorrect REST endpoint

---

README.md

The version badge was still referencing the old GitHub repo
(`PowerShell/PowerShellForGitHub) and was causing some issues.
Migrating it to point to the new `microsoft/PowerShellForGitHub` repo.

Fixing version badge on README

---

CONTRIBUTING.md
GitHubRepositories.ps1
PowerShellForGitHub.psd1
Tests/GitHubRepositories.tests.ps1

This adds the ability to easily rename a repository via the new cmdlet `Rename-GitHubRepository`, as suggested in #144 .  As we see in the diff, this PR:
- adds the new cmdlet
- adds a test for the new cmdlet
- adds a new contributor
Running `PSScriptAnalyzer` returns no issue (returned `$null`), and `Pester` test results were unchanged except that there is now one new, successful test.
How does this look as an add to this great module?

Add ability to rename a repository: Rename-GitHubRepository

---

build/pipelines/azure-pipelines.ci.yaml

Per this blog post https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/

Updating macOS image used in CI pipeline

---

CONTRIBUTING.md
Tests/Common.ps1

AppVeyor hasn't been in use since d6c3b5354bfaa6538123798cc97f684f273140de

Remove AppVeyor references from docs and code

---

Tests/Common.ps1

89f69f1132505f04e6b2ac38b6f5a93aef6ac947 introduced the usage of
`Get-SHA512Hash` to determine if the Settings.ps1 file had been
altered, however that's a non-exported function.
This now loads `Helpers.ps1` into the context of the Pester test
execution so that the function can be found.

Make Get-SHA512Hash available for use during Pester execution

---

GitHubRepositories.ps1

Fixing a typo introduced in 536b762425d51a181166c2c47ad2b00014911d1d

Fix typo from 536b762425d51a181166c2c47ad2b00014911d1d

---

Helpers.ps1

When this module was originally written, it used a special feature
of Write-Host in order to re-write the previously written line, in
order to show the user an indeterminate waiting indicator while the
module awaited a response from the server for a REST API request.
Unfortunately, this doesn't work well with all PowerShell hosts
(PowerShell ISE is one notable example).  This approach had been taken
originally as it had seemed odd to use Write-Progress (which displays
an absolute progress percentage) for something where we didn't absolutely
know the final duration.
This change migrates the module over to use Write-Progress, and simply
loops through the displayed percentage completed in the same manor that
it loops through and shows an animation.
This method should achieve the same desired …

Migrate REST API progress status to use Write-Progress

---

Helpers.ps1

Per helpful feedback from @StartAutomating:
>Taking a brief look at implementation, I don't see where you send -Completed message to Write-Progress.
>
>This will cause progress bars to stay visible while any other commands in the script execute.  E.g. if you ran a Get- that returned many results, and piped to an expensive Foreach-Object, your progress bar wouldn't go away until the Foreach-Object ended."

Ensure progress bar for Wait-JobWithAnimation gets marked as Completed

---

GitHubCore.ps1
GitHubRepositories.ps1
Tests/GitHubRepositories.tests.ps1

There were a few problems with this function:
* -GetAllPublicRepositories didn't actually work.  That's now been fixed,
and support for the optional Since paramater has been added as well.
* Fixed the ParameterSet handling for all of the parameters to make sure
that users can only specify parameters relevant with the appropriate
parameter set given that there are five different use cases for this
method:
* Getting repos for the current authenticated user
* Getting repos for any GitHub user
* Getting repos for an organization
* Getting all public repos)
* Getting a specific GitHub repo
Resolves #178
Helps with #139

Fix the behavior of Get-GitHubRepository

---

GitHubConfiguration.ps1
build/pipelines/azure-pipelines.ci.yaml

A CI check is failing because this value is wrong

Fixing the hash of the Tests/Config/Settings.ps1

---

GitHubAnalytics.ps1
GitHubAssignees.ps1
GitHubBranches.ps1
GitHubComments.ps1
GitHubCore.ps1
GitHubIssues.ps1
GitHubLabels.ps1
GitHubMilestones.ps1
GitHubMiscellaneous.ps1
GitHubOrganizations.ps1
GitHubProjectCards.ps1
GitHubProjectColumns.ps1
GitHubProjects.ps1
GitHubRepositoryForks.ps1
GitHubRepositoryTraffic.ps1
GitHubTeams.ps1
GitHubUsers.ps1
Helpers.ps1
NugetTools.ps1
PowerShellForGitHub.psd1
Tests/GitHubProjectCards.tests.ps1
Tests/GitHubProjectColumns.tests.ps1
Tests/GitHubProjects.tests.ps1
build/scripts/Write-SignConfigXml.ps1

Somehow a number of PSScriptAnalyzer issues have snuck in over time.  This fixes them all.
The main PSScriptAnalyzer issues needing to be fixed were:
* `PSReviewUnusedParameter` - This one came up a lot due to our heavy
usage of `Resolve-RepositoryElements` and `Resolve-ParameterWithDefaultConfigurationValue`
which both end up referencing their parameters by grabbing them off
the stack.  That means that `NoStatus` and `Uri` are frequently
never directly referenced.  So, exceptions were added.  There were
two cases (in GitHubAnalytics) where there was a false positive due
to PowerShell/PSScriptAnalyzer#1472
* `PSUseProcessBlockForPipelineCommand` - We had a number of functions
that took pipeline input, but didn't actuall use the `process` block.
This actually caught a bug with …

Get PSScriptAnalyzer clean again

---

GitHubConfiguration.ps1
README.md

Update usage documentation for configuring authentication unattended

---

GitHubBranches.ps1

We erroneously were putting a question mark in the middle of the
URI fragment when a branch name was being specified.
Resolves #187

Fix named branch querying in Get-GitHubRepositoryBranch

---

GitHubRepositories.ps1

GitHub free plans have changed and now private repos no longer
require a paid plan.
Resolves #190

Remove references to paid plans from documentation

---

GitHubRepositories.ps1

Incorrectly used `$PSBoundParameters.Contains` instead of
`$PSBoundParameters.ContainsKey`.
Resolves #195

Exception in New-GitHubRepository when specifying TeamId

---

UpdateCheck.ps1

Publishing a new version to PowerShellGallery happens a few hours after
the version is updated in GitHub.  This edge-case meant that someone
in this state would have been told that the older published version was
newer than the version that they were currently using.

UpdateCheck must handle when module is newer than published version

---

Tests/Common.ps1

Suppressing Status (e.g. using `-NoStatus`) reduces the overall runtime of the UT's across all 3 platforms (Windows, Linux, Mac) by 25-30 min.  It also has the side-effect of improving the readability of the raw logs on CI for Linux and Mac.
[Most recent run](https://dev.azure.com/ms/PowerShellForGitHub/_build/results?buildId=84315) without this change: 1h 19m
[Run with this change](https://dev.azure.com/ms/PowerShellForGitHub/_build/results?buildId=84357) without this change: 54m
Resolves #206

Speed up Pester tests by using -NoStatus

---

Tests/Common.ps1

We don't get any value from this update check when running the tests.

Disable the module update check during Pester Tests

---

build/pipelines/azure-pipelines.ci.yaml
build/pipelines/templates/run-staticAnalysis.yaml
build/scripts/ConvertTo-NUnitXml.ps1

This will now convert the output of `Invoke-ScriptAnalyzer` into an NUnitXml file that can then be published through the CI system so that we can fail on ScriptAnalyzer failures, as well as easily
see them in the test output.
Got the initial idea for this approach from @MathieuBuisson's [blog post](https://mathieubuisson.github.io/psscriptanalyzer-first-class-citizen/) (which directly converted the ScriptAnalyzer results into an NUnit XML file, but only had a single passing test for the success scenario).  I then combined that idea with one from a [Dr. Scripto post](https://devblogs.microsoft.com/scripting/psscriptanalyzer-deep-dive-part-3-of-4/) which used Pester to invoke PSScriptAnalyzer, ensuring that there was a test created for each possible Rule.  The problem with the Dr. Scripto …

Add NUnit Test handling for PSScriptAnalyzer results

---

GitHubCore.ps1

WhatIf support has now been simiplified in all API's that eventually
call into `Invoke-GHRestMethod`.  There's now a single check at the
top of that function which checks if it should continue or not.  If it
shouldn't, it early returns in order to avoid any code that might access
uninitialized content from outside of the ShouldProcess blocks later on.
Resolves #197

Fix handling of -WhatIf in core functions

---

GitHubRepositories.ps1

This PR fixes the exception in the `Set-GithubRepositoryTopic` function when the `Clear` parameter is specified.
- Fixes #215 
https://developer.github.com/v3/repos/#replace-all-repository-topics - Send an empty array ([]) to clear all topics from the repository.
is reporting back clean.

Set-GitHubRepositoryTopic: Fix Exception When Clear 'Parameter' is Specified

---

GitHubConfiguration.ps1

This PR adds `PositionalBinding = $false` to the `Set-GitHubConfiguration` function as discussed in Issue #219. 
None
N/A

Set-GitHubConfiguration: Add PositionalBinding = $false

---

GitHubContents.ps1
GitHubCore.ps1
GitHubIssues.ps1
GitHubMiscellaneous.ps1
GitHubReleases.ps1
GitHubRepositories.ps1
GitHubRepositoryForks.ps1
Tests/GitHubMiscellaneous.tests.ps1

There are only four legitimate instances in the module as of today where we should be disabling the validation that Resolve-RepositoryElements provides.  All other instances were likely introduced due to mistaken copy/paste issues.
The only reason we'd want to disable the validation is if there are multiple parametersets that need to be considered for the function, where at least one _would_ require `OwnerName`/`RepositoryName` while at least one other one _would not_.
This would have meant that we would have attempted to call those GitHub endpoints with incomplete path information which would have most likely resulted in an error that we could have caught sooner without needing to invoke a web request.
I've fixed up all of these incorrect instances, and added a comment to the two …

Fix usage of Resolve-RepositoryElements -DisableValidation

---

.vscode/settings.json
CONTRIBUTING.md
GitHubAssignees.ps1
GitHubBranches.ps1
GitHubIssueComments.ps1
GitHubIssues.ps1
GitHubLabels.ps1
GitHubMilestones.ps1
GitHubMiscellaneous.ps1
GitHubOrganizations.ps1
GitHubPullRequests.ps1
GitHubReleases.ps1
GitHubRepositories.ps1
GitHubRepositoryForks.ps1
GitHubRepositoryTraffic.ps1
GitHubTeams.ps1
GitHubUsers.ps1

Somehow two spaces got added after `'Description' =` in a function and then got copy/paste repeated throughout the module.
This fixes that.
It also adds a ruler line at the 100 character mark in VS Code to help developers see when they should start to wrap their code/comments.
n/a
n/a

Fix double-space added after 'Description' throughout module

---

build/pipelines/templates/run-staticAnalysis.yaml

Enhancement of #236 cc @HowardWolosky

Add more logging into catch block when PSScriptAnalyzer encounters a fatal error in CI

---

Tests/GitHubRepositoryForks.tests.ps1

This PR updates the upstream Owner and Repo name used in the `GitHubRepositoryForks` tests to cause less destruction.
None
N/A

GitHubRepositoryForks: Update Repo Name in Tests

---

GitHubRepositories.ps1
Tests/GitHubRepositories.tests.ps1

This PR updates the Pester tests for the `GitHubRepositories` module to increase the code coverage. This then exposed a code path in the `Get-GithubRepository` that could never be taken, so the function was refactored to remove this path and simplify the function logic.
A missing `ValidateSet` was also added to the `Affiliation` parameter of the `Get-GitHubRepository` function and incorrect Comment Based Help descriptions for the `Get-GitHubRepositoryCollaborator` and `Move-GitHubRepositoryOwnership` functions were fixed.
None
N/A

Update GitHubRepositories Tests and Refactor Get-GitHubRepository Function

---

UpdateCheck.ps1

* Fixes a regression [introduced by #242 unfortunately](https://github.com/microsoft/PowerShellForGitHub/commit/17f6122d7812ee4001ce4bdf630429e711e45f7b#diff-34a614678760cc83c5a91ad95ae240e5R86) when I was reducing the lines in the module that exceeded 100 chars.
Specifically:
https://github.com/microsoft/PowerShellForGitHub/blob/17f6122d7812ee4001ce4bdf630429e711e45f7b/UpdateCheck.ps1#L86
(note the `=Message` instead of the `-Message`)
* Updates the web request to suppress the progress bar using `$ProgressPreference = 'SilentlyContinue'`
* Adds a `-Force` switch to force the update check to happen again to make future debugging scenarios easier.
Fixes #249
Fixes #250
n/a

Invoke-UpdateCheck fixes

---

Tests/GitHubRepositoryForks.tests.ps1

Pull #251 changed the repo targeted by the forks tests from `microsoft/PowerShellForGitHub` to `octocat/Hello-World` in order to prevent the accidental deletion of real forks when running the UT's locally against your own account.
In practice, this almost doubled the execution time of the UT's, because the execution time of the Forks API's took so much longer against a repo with 1400+ forks.
Changing the test over to use a repo that currently only has 39 forks (several orders of magnitude fewer).
n/a
n/a

Improve CI speed by changing repo targeted by Forks tests

---

GitHubRepositories.ps1
Tests/GitHubRepositories.tests.ps1

Added in #221, `New-GitHubRepositoryFromTemplate was not capturing the passed-in value for the RepositoryName if provided via a Uri parameter.
There was a pipeline test in place, however it missed this fact because it was only testing the pipeline input scenario using `-WhatIf`, and the error was only found when calling the actual REST API and GitHub noticed that the `RepositoryName` was missing from the URI.
n/a
n/a

Fix pipeline support and testing for New-GitHubRepositoryFromTemplate

---

build/pipelines/azure-pipelines.ci.yaml
build/pipelines/templates/run-staticAnalysis.yaml
build/pipelines/templates/run-unitTests.yaml
build/pipelines/templates/verify-testConfigSettingsHash.yaml
build/pipelines/templates/wait-runningBuild.yaml
build/scripts/Wait-RunningBuild.ps1

This updates the CI build with two new features:
1. **Validation against Windows PS7 (PowerShell Core)**
This pipeline previously had three platforms that it tested against:
* `Windows PS5`
* `Linux PS7 (PowerShell Core)`
* `macOS PS7 (PowerShell Core)`
With this change, we add a fourth platform: `Windows PS7 (PowerShell Core)`
2. **Build queuing**
The unit tests operate against live GitHub accounts (as opposed to mocking out the execution of the API calls).  Each platform has its own account that it operates against to alllow each platform to be tested in parallel.  However, if more than one build is queued at once, then the builds can start to stomp over the expected state in the tests accounts.  This change adds a new `job` to the pipeline which will create a "queue" of running builds …

CI Build updates: build queuing and Windows PS7

---

GitHubConfiguration.ps1

`ConvertFrom-Json` defaults numbers to different types depending on the PowerShell version.
PS5 defaults numbers to `[Int32]` while PS7 defaults numbers to `[Int64]`, but both versions default to `[Int32]` in a `[PSCustomObject]`.
Due to this, if you had a number config value saved, on PS7 it would be ignored and the default value would be used because the expected and actual types wouldn't match.
I've updated `Resolve-PropertyValue` to have equivalence logic for number types to avoid this issue.
n/a
n/a

Fix handling of numerical configuration properties across PS5 and PS7

---

Tests/Common.ps1
Tests/GitHubAssignees.tests.ps1
Tests/GitHubContents.tests.ps1
Tests/GitHubIssues.tests.ps1
Tests/GitHubLabels.tests.ps1
Tests/GitHubProjects.tests.ps1
Tests/GitHubRepositories.tests.ps1
Tests/GitHubRepositoryForks.tests.ps1

We're seeing some inconsistent failures in some of the Pester tests.
The hypothesis is that GitHub may need a little bit more time after the creation of objects before performing certain operations on them (like renaming repos), or may need more time after deleting them before it will successfully return a 404 on a successive Get request.
I have added a number of `Start-Sleep`'s throughout the test codebase wherever we've encountered inconsistent failures, and that appears to have resolved the problem.  We may need to continue to do more of these if additional ones pop up.
The duration of the sleep itself is controlled by `$script:defaultSleepSecondsForReliability` which is defined in `Tests/Common.ps1`.
Long term, I have opened #267 which poses the idea of switching over to mocking out …

Attempting to increase reliability of some Pester tests

---

GitHubConfiguration.ps1
GitHubCore.ps1
Tests/Common.ps1
Tests/GitHubAssignees.tests.ps1
Tests/GitHubContents.tests.ps1
Tests/GitHubIssues.tests.ps1
Tests/GitHubLabels.tests.ps1
Tests/GitHubProjects.tests.ps1
Tests/GitHubRepositories.tests.ps1
Tests/GitHubRepositoryForks.tests.ps1

This is re-implementing #265 in a more robust way, thanks to a suggestion from @X-Guardian in #267.
Instead of adding in one-off sleeps throughout the test codebase, there is now a new configuration value (`StateChangeDelaySeconds`) that will allow us to insert a delay before returning the result of _any_ state change request.
This should ideally consistently add reliability throughout the entire test codebase.
Fixes #264
n/a

Attempting to increase reliability of some Pester tests - take 2

---

GitHubAssignees.ps1
GitHubBranches.ps1
GitHubConfiguration.ps1
GitHubContents.ps1
GitHubCore.ps1
GitHubEvents.ps1
GitHubGistComments.ps1
GitHubGists.ps1
GitHubIssueComments.ps1
GitHubIssues.ps1
GitHubLabels.ps1
GitHubMilestones.ps1
GitHubMiscellaneous.ps1
GitHubOrganizations.ps1
GitHubProjectCards.ps1
GitHubProjectColumns.ps1
GitHubProjects.ps1
GitHubPullRequests.ps1
GitHubReactions.ps1
GitHubReleases.ps1
GitHubRepositories.ps1
GitHubRepositoryForks.ps1
GitHubRepositoryTraffic.ps1
GitHubTeams.ps1
GitHubUsers.ps1
Helpers.ps1

The `NoStatus` parameter (and `DefaultNoStatus` config value) were deprecated as part of #253 when we stopped showing status except for multi-page requests that exceeded some minimum number of pages.
At that time, `NoStatus` (and `DefaultNoStatus`) were not removed in order to minimize the churn to the module.  However, keeping it in is adding unnecessary complexity to the module as we continue to expand what the module can do.
This change removes `NoStatus` (and `DefaultNoStatus`) from the module entirely.  The only impact that this may cause is with users who are currently using one (or both) of them.  This breaking change impact should be minimal, but its best for the breaking change to be part of the coming release which already has a number of other breaking changes as well, as …

Removing NoStatus from the module

---

GitHubBranches.ps1
Tests/GitHubBranches.tests.ps1

* Updates `New-GitHubBranch` to be able to take a `GitHub.Branch` object as pipeline input (for the base branch)
* Updates `New-GitHubBranch` to be able to take in a `Sha` so that a branch can be created from an arbitrary commit (which also enables a new branch to be created from a `GitHub.Branch` pipeline input value without needing to perform an additional query on `BranchName` to get its `Sha`)
* Updates `GitHub.Branch` to have `Sha` as a top-level property.
* Updated existing tests and added additional tests.
Fixes #261
[GitHub Refs API](https://developer.github.com/v3/git/refs/)

Update New-GitHubBranch pipeline support

---

Formatters/GitHubTeams.Format.ps1xml
GitHubTeams.ps1
PowerShellForGitHub.psd1
Tests/Common.ps1
Tests/GitHubTeams.tests.ps1

#257 did a fantastic job closing the gap on missing functionality in the module related to GitHub Teams.
This PR just adds onto that work by providing options that will reduce the need for additional queries during common operations.
* `Get-GitHubTeam`: **Breaking Change** Looking up a team by its `ID` has been deprecated per GitHub documentation.  Removed that functionality and added the ability to look up by `slug` instead.  This also means that you can now pipe in a team and get back the specific result without needing to filter through all org results.
* `Get-GitHubTeamMember`: Updated to use the `slug` instead of the team `ID`.
* `New-GitHubTeam`: Added ability to pass in the `ParentTeamId` (also via the pipeline) to avoid the need to query through all org teams.
* `Set-GitHubTeam`: …

Improvements to GitHub Team API's

---

CHANGELOG.md
GitHubContents.ps1
GitHubIssueComments.ps1
GitHubPullRequests.ps1
GitHubRepositories.ps1
GitHubUsers.ps1

Added a number of additional details for the breaking changes being introduced in order to make it easier for existing users to migrate their code.
Some very minor changes have been additionally made to fix some documentation or parameter typename issues.  Given that 0.15.0 still hasn't been officially published yet, these changes will be part of the eventual 0.15.0 release.
n/a
n/a

Enhancing CHANGELOG for 0.15.0

---

GitHubConfiguration.ps1
USAGE.md

In Azure Function Apps, the special `MyDocuments` folder resolves to an empty string, which means that the default `logPath` gets stored as an empty string.
https://github.com/microsoft/PowerShellForGitHub/blob/3094c9789caf00382134a0703344f655b13a1e33/GitHubConfiguration.ps1#L650-L657
https://github.com/microsoft/PowerShellForGitHub/blob/3094c9789caf00382134a0703344f655b13a1e33/GitHubConfiguration.ps1#L671
This causes problems when `Write-Log` is called by any other function, because we directly assign the current configuration value for `LogPath` as the parameter's default, which throws an exception when an empty string is assigned.
https://github.com/microsoft/PowerShellForGitHub/blob/3094c9789caf00382134a0703344f655b13a1e33/Helpers.ps1#L142
In this scenario, we'll fall back to using …

Fix default logPath when no user profile is available

---

GitHubAssignees.ps1
GitHubCore.ps1
GitHubEvents.ps1
GitHubIssueComments.ps1
GitHubLabels.ps1
GitHubMilestones.ps1
GitHubProjectCards.ps1
GitHubProjectColumns.ps1
GitHubProjects.ps1

Now that we are generating help documentation for the module, we want to ensure that we have a .SYNOPSIS for every function CBH.
n/a
n/a

Add missing .SYNOPSIS to functions

---

GitHubConfiguration.ps1
GitHubCore.ps1
Tests/GitHubRepositories.tests.ps1

GitHub will return back a `202` response when the result for the query is not yet ready.  GitHub requests that we "give the job a few moments to complete, and then submit the request again."
We already had the configuration value `RetryDelaySeconds` which covered how many seconds we would sleep before trying the request again. We tried the request again via a recursive call to `Invoke-GHRestMethod`.
It turns out that there's something going on with GitHub right now, and trying to get contributor statistics for a completely new repository never returns back a 200, even after 145 retry attempts over 72 minutes.
That many recursive calls ends up causing a call depth overflow exception with PowerShell.  While this scenario should be an edge-case, nonetheless it seems better to remove the …

Fix potential call depth overflow error when retrying a 202 response

---

CHANGELOG.md
PowerShellForGitHub.psd1

Update the module to `0.16.0`.
n/a
n/a

Update module to 0.16.0

---

build/pipelines/templates/prepare-release-internalOnly.yaml

The functionality is not currently being used, and keeping it enabled will cause this pipeline to stop being supported.

Disable DFS for release builds

---

GitHubCore.ps1

When experimenting with the the notifications API, it was necessary to be able to specify an additional header (If-Modified-Since).
Making this support generic by allowing callers to specify any number of additional headers to be included with the REST request.
n/a
[Notifications API](https://docs.github.com/en/rest/reference/activity#notifications) (although this doesn't actually implement anything from there)

Allow callers of Invoke-GHRestMethod[MultipleResult] to specify additional headers

---

Tests/GitHubGists.tests.ps1

octocat recently updated all of its gists, starting on 2/24/2021.
The test previously would query for gists that were updated since 2016, but as of 2/24/2021, that included all of them.
The test has been made more robust by choosing the most recent date of all the gists and then requerying, which should hopefully now always guarantee that we'll get a reduced set of gists, unless all of the gists are suddenly updated in the future at the exact same second.
n/a
[gist reference](https://docs.github.com/en/rest/reference/gists#get-a-gist)

Fix gist test validating the since parameter

---

GitHubContents.ps1

Fix Set-GitHubContent Encode Issues

---

GitHubConfiguration.ps1

Would be a copy-paste error from `-DefaultOwnerName`.

Fix help: Set-GitHubConfiguration -DefaultRepositoryName

---

GitHubCore.ps1

Doing some clarifying wording in the friendly error message that we add to a 404 to indicate that they could be getting the error because the item truly doesn't exist, not simply due to authentication issues.
Came up due to confusion in #354

Improve the 404 friendly message

---

GitHubRepositories.ps1

The Get/Set/Remove-GitHubRepositoryTeamPermission functions will sometimes call Get-GitHubTeam to get missing information.  In those instances, they weren't passing along the `AccessToken` parameter if it had been provided by the user.  In those scenarios, the result will be a 404 since the Get-GitHubTeam call won't have the same auth permissions as the core API being called.
Fixes #353

Not forwarding AccessToken to sub-commands for Repo Team Permissions

---

GitHubRepositories.ps1

When retrieving the permissions granted to a team for a repository, the API returns an array of booleans indicating what individual permissions the team currently has.
| name | permissions granted |
| ---- | ------------------ |
| pull | pull |
| triage | pull, triage |
| push | pull, triage, push |
| maintain | pull, triage, push, maintain |
| admin | pull, triage, push, maintain, admin |
As you can see, each permissions builds on top of the previous
permission.  When adding extra properties to this returned object
via `Add-GitHubRepositoryTeamPermissionAdditionalProperties`, we
also add a new `permission` property that attempts to represent the
collection of permissions with their current top-permission level.
The logic however incorrectly favored `push` over `maintain` and thus
would …

Fix coalesced Team permission property

---

GitHubRepositories.ps1
Tests/GitHubRepositories.tests.ps1

Reverts microsoft/PowerShellForGitHub#358
It turns out that this isn't quite working right.
The `use_squash_pr_title_as_default` parameter [has been deprecated per the documentation](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#update-a-repository) in favor of `squash_merge_commit_title ` which works a bit differently.
Additionally, there appears to be a GitHub-side bug at the moment with changing the value of `allow_auto_merge` (it does not honor the request being sent).
Given this, for the time being we'll revert the change until we know that the feature is working correctly.
/cc: @X-Guardian

Revert "New/Set-GitHubRepository: Add AllowAutoMerge and UseSquashPrTitleAsDefault Parameters"

---

GitHubRepositories.ps1
Tests/GitHubRepositories.tests.ps1

This PR adds the `AllowAutoMerge` parameter to the `New-GitHubRepository` and `Set-GitHubRepository` functions:
Note: this feature is currently only supported by GitHub on public repositories.
- Fixes #357 
- https://docs.github.com/en/rest/repos/repos#create-an-organization-repository

New/Set-GitHubRepository: Add AllowAutoMerge Parameter

---

GitHubRepositories.ps1
Tests/GitHubRepositories.tests.ps1

This PR adds the `AllowUpdateBranch` parameter to the `New-GitHubRepository` and `Set-GitHubRepository` functions:
- Fixes #386
- https://docs.github.com/en/rest/repos/repos#create-an-organization-repository

New/Set-GitHubRepository: Add Support for 'Allow Update Branch' Option

---

GitHubRepositories.ps1
Tests/GitHubRepositories.tests.ps1

This PR adds the `WebCommitSignoffRequired` parameter to the `Set-GitHubRepository` function:
- Fixes #388

Set-GitHubRepository: Add Support for 'Web Commit Signoff Required' Option

---

Formatters/GitHubDeployments.Format.ps1xml
GitHubDeployments.ps1
PowerShellForGitHub.psd1
README.md
Tests/GitHubDeployments.tests.ps1
USAGE.md

This PR adds the following new cmdlets for managing GitHub Deployment Environments:
- `New-GitHubDeploymentEnvironment`
- `Get-GitHubDeploymentEnvironment`
- `Set-GitHubDeploymentEnvironment`
- `Remove-GitHubDeploymentEnvironment`
- Fixes #394
-  [Deployment Environments](https://docs.github.com/en/rest/deployments/environments)

API Coverage: Add Support for Deployment Environments

---

GitHubRepositories.ps1
Tests/GitHubRepositories.tests.ps1

This PR adds merge commit message and title parameters to the `New-GitHubRepository` and `Set-GitHubRepository` functions:
- Fixes #384
- https://docs.github.com/en/rest/repos/repos#create-an-organization-repository

New/Set-GitHubRepository: Add Support for Merge Commit Title and Message Options

---

Tests/GitHubDeployments.tests.ps1

I generally don't like aliases being used (neither does PSScriptAnalyzer), but in this case, `New-GitHubDeploymentEnvironment` was writting to be able to behave as `Set-GitHubDeploymentEnvironment` as well, and we should be testing it the way that a user would likely be calling it.
- ~~[ ] Comment-based help added/updated, including examples.~~
- ~~[ ] New/changed code adheres to our [coding guidelines](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#coding-guidelines).~~
- ~~[ ] [Formatters were created](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#formatters) for any new types being added.~~
- ~~[ ] New/changed code continues to [support the pipeline](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md# …

Remove static analysis warning for using a module alias being referenced in a test
