- GitHubAnalytics.psm1
- Tests/GitHubAnalytics.tests.ps1
Added the Get-GitHubRepositoryBranch function to get all branches for a given repository
> #19 Adding method to get branches for repository

- GitHubAnalytics.psm1
- GitHubLabels.psm1
- Tests/GitHubAnalytics.tests.ps1
- Tests/GitHubLabels.tests.ps1
> Update all parameters to use PascalCase

- CHANGELOG.md
- CONTRIBUTING.md
Updating the data in CHANGELOG for 0.2.0, and fixing a formatting typo in CONTRIBUTING.
> Minor fixes to CHANGELOG and CONTRIBUTING

- Tests/GitHubMilestones.tests.ps1
We should be comparing a Date to a Date
> Fix Milestones.tests due_on DateTime issue

- GitHubRepositories.ps1
This is a small typo fix. Haven't touched anything else.
> Small typo fix

- CONTRIBUTING.md
- GitHubAnalytics.ps1
- GitHubAssignees.ps1
- GitHubBranches.ps1
- GitHubComments.ps1
- GitHubConfiguration.ps1
- GitHubContents.ps1
- GitHubCore.ps1
- GitHubEvents.ps1
- GitHubIssues.ps1
- GitHubLabels.ps1
- GitHubMilestones.ps1
- GitHubMiscellaneous.ps1
- GitHubPullRequests.ps1
- GitHubReleases.ps1
- GitHubRepositories.ps1
- GitHubRepositoryForks.ps1
- GitHubRepositoryTraffic.ps1
- GitHubTeams.ps1
- GitHubUsers.ps1
- Helpers.ps1
- Telemetry.ps1
- Tests/GitHubAnalytics.tests.ps1
Noticed a typo - then went on a spelling hunt.. I'm done for now, I'll stop bothering you for a bit :)
> Spelling fixes

- .github/ISSUE_TEMPLATE/Documentation.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Problem.md
- .github/ISSUE_TEMPLATE/Support.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
These were heavily influenced by the wonderful templates in use at
https://github.com/dsccommunity/ActiveDirectoryDsc/tree/master/.github/
> Add issue and pull request templates

- Tests/GitHubRepositories.tests.ps1
This PR fixes the `Describe 'GitHubRepositories\Enable-GitHubRepositorySecurityFix'` and `Describe 'GitHubRepositories\Disable-GitHubRepositorySecurityFix'` GitHubRepositories tests following on from the change to the GitHub Automated Security Fixes API.
- Fixes #269 
[Enable Automated Security Fixes](https://docs.github.com/en/rest/reference/repos#enable-automated-security-fixes)
> Fix GitHubRepositorySecurityFix tests

- GitHubRepositories.ps1
- Tests/GitHubRepositories.tests.ps1
This PR fixes the pipeline input for the following GitHub Repository functions:
- Disable-GitHubRepositoryVulnerabilityAlert
- Enable-GitHubRepositorySecurityFix
- Disable-GitHubRepositorySecurityFix
The unit tests for the functions are also updated to add pipeline tests.
- Fixes #270 
N/A
> Fix GitHub Repository `Dependabot` Functions Pipeline Input

- CHANGELOG.md
- PowerShellForGitHub.psd1
Updating the module version and and CHANGELOG in preparation for a release of v0.15.0
n/a
n/a
> Updating module version to 0.15.0

- CHANGELOG.md
- PowerShellForGitHub.psd1
Update the module to `0.15.1`.
n/a
n/a
> Update module to 0.15.1

- USAGE.md
Documentation mistake
- Fixes #287
> Fix typos in USAGE.md

- build/scripts/Build-Wiki.ps1
This adds a new script utilitity, Build-Wiki.ps1, which can be used to auto-generate the documentation for the Wiki.  This uses the
[PlatyPS](https://github.com/PowerShell/PlatyPS) module to generate the actual help documentation.
Relevant notes:
* This will generate the `Home.md`, `_sidebar.md`, and `_footer.md`   files for the Wiki if they don't already exist in the destination
directory.
* If they do already exist, it intelligently updates the content,  only replacing the parts that it generated itself (denoted with
comments in the markdown content itself).
* At present, this is not being hooked-up to CI because I don't want  to deal with storing credentials that have admin access to the actual repo.
Tip of the hat to @X-Guardian for the suggestion and the initial help with writing …
> Auto-generate documentation for Wiki

- GitHubContents.ps1
Fixed the variable check for Set-GitHubContent. This issue was mentioned by @amis92 and issued in #285 
- Fixes #285
> Fixed a copy-paste error

- USAGE.md
This PR changes an opening brace to parenthesis because Add-GitHubIssueLabel takes an array of label strings.
None
> Fix typo in example in USAGE.md

- USAGE.md
Add a reference to the documentation in the Wiki to the top of USAGE.md.
n/a
n/a
> Add reference to Wiki in USAGE.md

- USAGE.md
> Fix markdown for example in USAGE.md

- GitHubEvents.ps1
- GitHubLabels.ps1
The Get-GitHubEvent is currently broken if the issue contains and event that includes the "label" or "labels" property. This is because Add-GitHubEventAdditionalProperties treats the labels in the event object as full fledged label objects that normally contain a URL property and other additional pieces of data. The label property in events is a lighter-weight object that simply contains the string for the label and color that was changed, it is not the full object that you would typically receive from a call like Get-GithubLabel.
none
The docs do not explicitly call this out, but you can check the payload in fiddler for verificaiton.
> Fix labels in events being treated as full label objects

- USAGE.md
Fixes the example in USAGE.md for `New-GitHubRepositoryFromTemplate`.  The current example uses the original syntax that was changed during code review.
Fixes #308
> Fix the USAGE.md example for New-GitHubRepositoryFromTemplate

- CONTRIBUTING.md
- build/scripts/Build-Wiki.ps1
Fixed some issues with `Build-Wiki`:
* Ensured that `Home.md` is not incorrectly categorized as deprecated.
* Fixed how we check for `platyPS` being installed.
* Fixed how we reference files in `Move-Item` to solve the issue when the file being moved is new.
* Added warning/reminder to run this under `PS7+` to avoid issue with how multi-line examples get formatted.
Also added Wiki updating instructions to the release section of `CONTRIBUTING.md`.
n/a
n/a
> Fix issues with Build-Wiki and add Wiki documentation to CONTRIBUTING.md's Release section

- USAGE.md
> Fixed typo in New-GitHubRepositoryFork for USAGE.md

- Telemetry.ps1
The telemetry code was creating a singleton base telemetry event the first time that telemetry was being sent.  That base event included the date.  If a PowerShell session lasted multiple days, the telemetry reporting would eventually start to fail because the date being reported for the event was too old.
We now just create a new telemetry event every time one is requested (this also ensures that it honors changes to the `ApplicationInsightsKey`), and now we only cache a GUID that we use to represent the "session" ID which we consider to be the duration of the current PowerShell session.
None
> Fix telemetry failure for long-running sessions

- GitHubRepositories.ps1
- Tests/GitHubRepositories.tests.ps1
This PR adds the following parameters to the `New-GitHubRepository` and `Set-GitHubRepository` functions:
- `AllowAutoMerge`
- `UseSquashPrTitleAsDefault`
- Fixes #357 
- https://docs.github.com/en/rest/repos/repos#create-an-organization-repository
> New/Set-GitHubRepository: Add AllowAutoMerge and UseSquashPrTitleAsDefault Parameters

- Tests/GitHubRepositories.tests.ps1
Remove the `has_wiki` property check from the private repositories unit tests as Wikis are no longer supported on the GitHub free tier.
- Fixes #403
N/A
> GitHubRepositories: Remove `has_wiki` Check from Private Repositories Unit Tests

- GitHubRepositories.ps1
- Tests/GitHubRepositories.tests.ps1
This PR adds the `SecretScanning` parameter to the `Set-GitHubRepository` function:
Note: The parameter was implemented using the `Enabled, Disabled` parameter validate set rather than a switch to mirror the pattern used by the GitHub API.
- Fixes #390
> Set-GitHubRepository: Add Support for 'Secret Scanning' Option
